README.md
I added the mpl_finance download path in README file
=> Add mpl_finance download path

.prospector.yaml, Bar.py, NN.py, Position.py, VirtualAccount.py, demo/3D_OAT.py, dl_test.py, finance_utils.py, getYahooFinanceData.py, nn_test.py, pandas_test.py, playground.py, stock_db_mgr.py, technical_indicators.py, tester.py, tmxstockquote.py, tradesim.py
=> Python3 print conversion

.travis.yml, requirements.txt
=> code coverage test

technical_indicators.py, tradesim.py
Fix issue #13 
technical indicator method naming not up to standard
=> refactor function name

technical_indicators.py, test/test_technical_indicators.py
write dummy tests at least to exercise the functions
=> test technical indicators

finance_utils.py, test/test_finance_utils.py
Implemented optional inplace=False for fill_nan_data.
=> Fill na inplace

finance_utils.py, rebalance.py, test/test_finance_utils.py, test/test_virtual_account.py, tradesim.py, virtual_account.py
=> Rebalance refactor 2

demo/demo_finance_utils.py, dl_validation.py, finance_utils.py
=> Fix yahoo duplicate date

test/test_ystockquote.py, ystockquote.py
=> Fix yfinance dividend

stock_db_mgr.py, test/test_marker.py, yqd.py
tests PR with review
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mathieugouin/tradesim/44)
=> Test review

.github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mathieugouin/tradesim/45)
=> Updated ci jobs versions

demo/demo_stock_db_mgr.py, demo/parent_import.py, stock_db_mgr.py
Fixes #46
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mathieugouin/tradesim/48)
=> Dataframe performance warning

demo/demo_finance_utils.py, demo/demo_stock_db_mgr.py, finance_utils.py, test/test_finance_utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mathieugouin/tradesim/52)
=> Load_df_perf

.github/workflows/ci.yml, playground.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mathieugouin/tradesim/53)
=> More coverage in the CI script

.github/workflows/ci.yml
Ref:
https://community.codecov.com/t/upload-issues-unable-to-locate-build-via-github-actions-api/3954
https://github.com/marketplace/actions/codecov
https://app.codecov.io/gh/mathieugouin/tradesim/settings
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mathieugouin/tradesim/55)
=> try codecov token

demo/demo_finance_utils.py, finance_utils.py, stock_db_mgr.py, test/test_finance_utils.py, test/test_stock_db_mgr.py
New method to properly validate financial data at the dataframe level.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mathieugouin/tradesim/57)
=> Validate dataframe

.github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mathieugouin/tradesim/59)
=> Simplify CI builds

finance_utils.py
Fixes #58
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mathieugouin/tradesim/63)
=> fillna deprecation warning

.github/workflows/ci.yml, pytest.ini, test/test_examples.py, test/test_finance_utils.py, test/test_stock_db_mgr.py, test/test_utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mathieugouin/tradesim/62)
=> Test cleanup

.bandit.yaml, .github/workflows/ci.yml, .gitignore, .prospector.yaml, tests/test_utils.py, virtual_account.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mathieugouin/tradesim/65)
=> Run prospector

.github/workflows/ci.yml, finance_utils.py, sonar-project.properties, tests/test_finance_utils.py, tests/test_position.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mathieugouin/tradesim/66)
=> Sonar fixes

.github/workflows/ci.yml, finance_utils.py, math_utils.py, rebalance.py, sonar-project.properties, tests/test_math_utils.py
multiple branch because tests with long-lived branches.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mathieugouin/tradesim/69)
=> Sonar fixes2

math_utils.py, technical_indicators.py, tests/test_finance_utils.py, tests/test_math_utils.py, tests/test_stock_db_mgr.py, tests/test_technical_indicators.py, tests/test_utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mathieugouin/tradesim/72)
=> Test refactor

.prospector.yaml, finance_utils.py, playground.py, position.py, rebalance.py, stock_db_mgr.py, tests/__init__.py, tests/test_technical_indicators.py, tests/test_ystockquote.py, virtual_account.py, yqd.py
Fix some prospector findings.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mathieugouin/tradesim/70)
=> Prospector Fixes

yqd.py
Fixes #71
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mathieugouin/tradesim/73)
=> Yahoo crumb simplification

update_stock_lists.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mathieugouin/tradesim/77)
=> Robustness for tsx update

finance_utils.py, get_yahoo_finance_data.py
Fixes #74
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mathieugouin/tradesim/79)
=> Remove python2 specific code

.coveragerc, .github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mathieugouin/tradesim/85)
=> Dynamic ctx

requirements.txt, ystockquote.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mathieugouin/tradesim/89)
=> Don't x100 for dividend

.coveragerc, .github/workflows/ci.yml, requirements.txt, ystockquote.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mathieugouin/tradesim/86)
=> Coverage Report

delete_historical_data.sh, get_yahoo_finance_data.py, stock_db/dj.txt, stock_db/sp500.txt, stock_db/tsx.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mathieugouin/tradesim/93)
=> Fix download script
